## Numpy basics and arrays


In [1]:
import numpy as np

## creating a numpy array

In [4]:
arr_1d=np.array([1,2,3])
print("the one dimen array is",arr_1d)

arr_2d=np.array([[1,2],[2,3]])
print("the two dimen array is",arr_2d)

the one dimen array is [1 2 3]
the two dimen array is [[1 2]
 [2 3]]


## List vs Numpy Array

In [11]:
py_list=[1,2,3,4,5]
print("python list multi",py_list*2)

np_array=np.array([1,2,3,4,5])
print("python array multi",np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("list time",time.time() - start)

start=time.time()
np_array=np.arange(100000) * 2
print("array time",time.time() - start)


python list multi [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
python array multi [ 2  4  6  8 10]
list time 0.005430936813354492
array time 0.0003330707550048828


## creating arrays from scratch

In [21]:
zeros=np.zeros((3,4))
print("zero array",zeros)

ones=np.ones((1,2))
print("ones array",ones)

full=np.full((2,2),5)
print("full array",full)

random=np.random.random((2,2))
print("random array",random)

seq=np.arange(0,11,2)
print("seq array",seq)




zero array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array [[1. 1.]]
full array [[5 5]
 [5 5]]
random array [[0.3884481  0.20175102]
 [0.48822224 0.20351277]]
seq array [ 0  2  4  6  8 10]


## vectors and matrices and tensor

In [23]:
vector = np.array([1,2,3])
print("vector is ",vector)

matrix = np.array([[1,2],[2,3]])
print("matrix is ",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor is ",tensor)


vector is  [1 2 3]
matrix is  [[1 2]
 [2 3]]
tensor is  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
print("the shape is:",arr.shape) 
print("the dimesnion is:",arr.ndim) 
print("the size is:",arr.size) 
print("the Dtype is:",arr.dtype) 

the shape is: (2, 3)
the dimesnion is: 2
the size is: 6
the Dtype is: int64


## Array Reshaping

In [32]:
original = np.arange(12)
print("original array is ",original)

reshaped = original.reshape((3,4))
print("reshaped array is ",reshaped)

flattened = reshaped.flatten()
print("flattened array is ",flattened)

## returns view, does not copy
raveled = reshaped.ravel()
print("RAVELED array is ",raveled)

transpose = reshaped.T
print("transposed array is ",transpose)


original array is  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array is  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array is  [ 0  1  2  3  4  5  6  7  8  9 10 11]
RAVELED array is  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array is  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
