## NumPy Array Operations

In [5]:
import numpy as np

arr = np.arange(10)
print("Basic Slicing:", arr[3:9]) 
print("With Step:", arr[3:9:2]) 
print("Negative Indexing", arr[-2]) 

Basic Slicing: [3 4 5 6 7 8]
With Step: [3 5 7]
Negative Indexing 8


In [10]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element",arr_2d[1,2])
print("Entire row",arr_2d[1,])
print("Enitre Column",arr_2d[:, 2])

Specific Element 6
Entire row [4 5 6]
Enitre Column [3 6 9]


## Sorting

In [20]:
arr = np.array([10,5,3,9,2,6])
print("Sorted Array is:",np.sort(arr))

arr_2d = np.array([[3,1],[2,3],[2,1]])
print("Sorted Array by Column:",np.sort(arr_2d, axis=0))
print("Sorted Array by Row:",np.sort(arr_2d, axis=1))

Sorted Array is: [ 2  3  5  6  9 10]
Sorted Array by Column: [[2 1]
 [2 1]
 [3 3]]
Sorted Array by Row: [[1 3]
 [2 3]
 [1 2]]


## Filter

In [23]:
arr = np.arange(11)
print("Filtered", arr[arr % 2 == 0])

Filtered [ 0  2  4  6  8 10]


## Filter with Mask

In [25]:
mask = arr > 5
print("Filter with mask", arr[mask])

Filter with mask [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [38]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [1,3,8]
print(numbers[indices])

where = np.where(numbers>5)
print(where)
print(numbers[where])

[2 4 9]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [ ]:
## np.where creates a new array usign an existing array. it deos not modify the existing array
condition = np.where(numbers>5, "true", "false")
print(condition)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and Removing Data

In [50]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print("concatenated array is", combined)

arr= np.array([[1,2],[3,4]])
new_row = np.array([5,6])

new_arr = np.vstack((arr, new_row))

print(arr)
print(new_arr)


new_column = np.array([[7],[8]])
new_arr_2 = np.hstack((arr, new_column))
print(new_arr_2)

num = np.array([1,2,3,4,5,6,7])
deleted = np.delete(num, 1)
print(deleted)

concatenated array is [1 2 3 4 5 6]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
[1 3 4 5 6 7]
